## Welcome to Jupyter Notebook
Welcome to Jupyter Notebook, one of the many ways that you can use Python. Jupyter notebooks run lines of code in what are called **cells**. This makes it convenient to run certain lines of code and see the output of those lines of code in real time.
To run a cell of code, simply press Shift + Enter.

### Python Functions
Python is a dynamically typed language, meaning you don't have to declare the types of variables. These are determined at runtime.
Also, Python uses spacing to determine scopes and groupings. For example, when you write a function, it will look like this:

In [80]:
#Function definition
def helloWorld():
    print("Hello World")

#Calling the function
helloWorld()


Hello World


Note that the **def** means we are defining a function. The colon is necessary for defining what is part of the function. Instead of using "{" and "}" like C++ or Java, everything that is part of the function needs to be spaced out separately (convention is 4 spaces or a tab). Incorrect spacing is a common reason for code not working properly.

### Tuples
One of Python's useful capabilities is its ability to pass and return tuples. For example, if you need to return two pieces of information from a function, you simply can name the two pieces of information and treat them as a tuple. Notice in the example below how perimeter and area can be returned at the same time.

In [81]:
def rectangleInfo(width, height):
    perimeter = 2*width + 2*height
    area = width * height
    return perimeter, area

myPerimeter, myArea = rectangleInfo(10,10)
print("My perimeter is", myPerimeter, "and my area is", myArea, ".")


My perimeter is 40 and my area is 100 .


### Default Parameters
Lastly, Python has a very simple default parameter value system. To state a default parameter, simply state what that parameter would be equal to if no parameter is given in the function description. Notice in the example below how startingNumber, stepSize, and numIters are all given default values if they are not specified in the function call.

In [82]:
def countByNum(startingNumber=1,stepSize=1,numIters=10):
    text = ""
    count = startingNumber
    for i in range(0,numIters):
        text += str(count)
        if i < numIters-1:
            text += ","
        count += stepSize
    print(text)

#The different ways to use default parameters 
countByNum()
countByNum(2, 2)
countByNum(stepSize=2)

1,2,3,4,5,6,7,8,9,10
2,4,6,8,10,12,14,16,18,20
1,3,5,7,9,11,13,15,17,19


## Practice 1: General Fibonaci Sequence
Write a function that takes in the number **n** (or *num*) and it returns the **(n-1)th** and **nth** Fibonacci numbers. Also, allow for the user to specify the **0th** and **1st** Fibonacci numbers that start off the sequence, but they should default to the standard ($n_0$=1 and $n_1$=1).

In [83]:
#Your code here

def fibonacci(num, n0 = 1, n1 = 1):
    
    #Base cases
    if num == 0:
        return n0, n0
    elif num == 1:
        return n0, n1

    #Starting Numbers
    prev = n0
    curr = n1

    #Iterate through the sequence
    for i in range(2,num + 1):
        next = prev + curr
        prev = curr
        curr = next

    #Return (n-1) and n
    return prev, curr





To test that your code is working, try finding the $n_5$ and $n_6$ Fibonacci numbers for $n_0 = 2$ and $n_1 = 2$. You should get 16 and 26 because the sequence would be (2, 2, 4, 6, 10, 16, 26).
The second print statement is how we will grade that you completed the task. **Do not delete any given test cases**.

In [84]:
#Test Cases
print( fibonacci(6, 2, 2) )
print( fibonacci(10) )
print( fibonacci(24, 3, 5) )

(16, 26)
(55, 89)
(196418, 317811)


# -------------------------------------------------------

### Data Structures - Lists
Python has two primary types of data structures built in: lists and dictionaries. These data types are the most commonly used for Python methods and programming. Other types of data structures can be imported as needed. Let's start with lists.

In [85]:
myList = [] #Square brackets initialize a list

#Add elements to the list
myList.append(3)
myList.append(4)
myList.append(7)
#Insert the number 10 at the 0th index
myList.insert(0, 10)

print(myList)

[10, 3, 4, 7]


In [86]:
#Accessing an element in a list
print(myList[1])
#Grab the last element in a list
print(myList[-1])

3
7


In [87]:
#Grab all elements in a list
print(myList[:])
#Grap a certain section of the list  
print(myList[0:2])

[10, 3, 4, 7]
[10, 3]


**Warning: Python excludes the last number in a range, as shown above. This is different from most common programming languages.** To see this, run the following code.

In [88]:
a = range(0,10)
print(list(a))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Going back to lists, Python has a very powerful list accessing system known as slice notation. It can be summarized as

**[ first element to include : first element to exclude : step ]**

Some common examples are given below.

In [89]:
myList2 = list(range(0,10))
print(myList2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [90]:
#Grab every other element in the list
print(myList2[::2])

#Grab every other element for the first 5 numbers
print(myList2[0:5:2])

#Reverse the list
print(myList2[::-1])

[0, 2, 4, 6, 8]
[0, 2, 4]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In Python, for loops are designed with lists in mind. You can see some examples below.

In [91]:
myList3 = [1, 5, 8, 19, 7, 6]
total = 0

# You may be tempted to do this
length = len(myList3)

for i in range(0, length):
    num = myList3[i]
    total += num
    
print(total)

46


The example above is a very Java-like way of doing list iteration, but there are better ways in Python. For example:

In [92]:
#It is much simpler to do this
total = 0

for num in myList3:
    total += num

print(total)

46


Note that Python can give you elements of a list as the iterator through a for loop. This is very helpful in many problems.

For more help with lists, you can visit https://docs.python.org/3/tutorial/datastructures.html

## Practice 2: List Manipulation
Write a function called listShift. This function should take the second half of a list, reverse it, and reappend it to the front of the list. For example,

[1, 2, 3, 4, 5, 6, 7, 8, 9]  would become [9,8,7,6,1,2,3,4,5]

As shown, odd number lists should not include the middle element in the reversed list.

Hint: This is a lot easier if you don't use a for loop.

In [93]:
#Your code here
def listShift(myList):
    midpoint = len(myList) // 2

    if len(myList) % 2 == 0:
        first_half = myList[:midpoint]
        second_half = myList[midpoint:]

    else:
        first_half = myList[:midpoint+1]
        second_half = myList[midpoint+1:]

    reverse_second_half = second_half[::-1]

    result = reverse_second_half + first_half

    return result

In [94]:
#Test Case
print(listShift([1,2,3,4,5,6,7,8,9]))
print(listShift([10,9,8,7,6,5,4,3,2,1,10,9,8,7,6,5,4,3,2,1]))

[9, 8, 7, 6, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


# -----------------------------------------------------

### Data Structures - Dictionaries
We won't be using dictionaries as much in this class, but it would be an injustice if you didn't get some exposure to them. They are one of the most powerful constructs in Python. The dictionary data structure is also sometimes known as a map data structure in other languages.

In [95]:
myDictionary = {} #Curly brackets initialize a dictionary

#Add elements to dictionary using key/value system
myDictionary["University"] = "ECU"
myDictionary["City"] = "Greenville"

print(myDictionary)

{'University': 'ECU', 'City': 'Greenville'}


In [96]:
#Another way to instatiate a dictionary
myDictionary2 = {'Name': 'Zara', 'Age': 7, 'Grade': '1'}
print(myDictionary2)

#Go through data in a dictionary
for key in myDictionary2:
    print(myDictionary2[key])

#Remove data
del myDictionary2["Grade"]
print(myDictionary2)

myDictionary2.clear()
print(myDictionary2)

{'Name': 'Zara', 'Age': 7, 'Grade': '1'}
Zara
7
1
{'Name': 'Zara', 'Age': 7}
{}


### Python Classes
Python can use object-oriented programming through the use of classes like most languages. However, the syntax for classes is very unique to Python.

Below is an example of a class in Python.

In [97]:
from math import pi

class Circle():
    
    def __init__(self, radius, center_x=0.0, center_y=0.0):
        self.radius = radius
        self.x = center_x
        self.y = center_y
        
    def getCircumference(self):
        return 2*pi*self.radius
    
    def getArea(self):
        return pi*self.radius**2
    
    def getArc(self, angle):
        return self.radius * angle
    
myCirc = Circle(25)
print(myCirc.getCircumference())
print(myCirc.getArea())
print(myCirc.getArc(1.5))

157.07963267948966
1963.4954084936207
37.5


Note the keyword **class** is used to start the definition. The constructor for the class is always defined within the **__init__** function. Any other functions can be named as needed.

Also, note that the keyword **self** must be passed into each function. This is where the variables for the class are stored. You can think of it similar to the **this** keyword in Java. However, note that this variable does not need to be passed in on call, only definition.

### Inheritance
Classes can also inherit methods and properties from other classes. This can be done by placing the name of the super class in the parenthesis of the class defintion. These super classes can also have abstract methods by using the keyword **pass**.

In [98]:
class Shape():
    
    def getPerimeter(self):
        pass
    
    def getArea(self):
        pass
    
class Square(Shape):
    
    def __init__(self, size):
        self.size = size
    
    def getPerimeter(self):
        return 4*self.size
    
    def getArea(self):
        return self.size**2
    
    
mySquare = Square(10)
if isinstance(mySquare, Shape):
    print(mySquare.getPerimeter())

40


For more information on classes in Python, see https://docs.python.org/3/tutorial/classes.html

## Practice 3: Push and Pop
Write your own class called MyPriorityQueue. This class should have two methods: **push** and **pop**. Push takes in a value and priority number and puts it in a dictionary. Pop returns the value with highest priority number and removes that value from the dictionary. 

In [99]:
class MyPriorityQueue():
    def __init__(self):
        self.queue ={}
    
    def push (self, value, priority):
        if priority not in self.queue:
            self.queue[priority] = []
        self.queue[priority].append(value)

    def pop(self):
        if not self.queue:
            raise IndexError("Queue is empty")
        
        highest_priority = max(self.queue.keys())

        value = self.queue[highest_priority].pop()

        if not self.queue[highest_priority]:
            del self.queue[highest_priority]

        return value

In [100]:
#Test Case
myQueue = MyPriorityQueue()
myQueue.push("were toiling upward in the night.", 2)
myQueue.push("The heights by great men reached and kept", 5)
myQueue.push("-Longfellow", 1)
myQueue.push("were not attained by sudden flight,", 4)
myQueue.push("but they, while their companions slept,", 3)
print(myQueue.pop())
print(myQueue.pop())
print(myQueue.pop())
print(myQueue.pop())
print(myQueue.pop())

The heights by great men reached and kept
were not attained by sudden flight,
but they, while their companions slept,
were toiling upward in the night.
-Longfellow


# -----------------------------------------------------

### Importing Packages in Python
Python has multiple ways to import packages to use in the system. The keywords you can use are **import**, **from**, and **as**.

In [101]:
import math
print(math.pi)

from math import pi
print(pi)

from math import pi as taco
print(taco)

from math import * #Import everything from the package
print(e)

3.141592653589793
3.141592653589793
3.141592653589793
2.718281828459045


One of the main packages we will use is called Numpy. It is a huge matrix processing library that is very helpful for image processing and graphics. The conventional import method looks like this.

In [102]:
import numpy as np
print(np.version.version)

1.24.4


Make sure that you have at least version 1.08 running. If you can't get the package to work, make sure that you run *pip install numpy* or *conda install numpy* in the command line according to the setup instructions.

Numpy allows you store matrices natively and do matrix operations in a single step.

Let's look at a simple matrix.

In [103]:
import numpy as np
a = np.matrix([[1, 2],[3,4]])

print(a)

[[1 2]
 [3 4]]


In [104]:
print(a[0,1]) #Row, Column zero-based indexing

2


In [105]:
print(a[:,1]) #Grab all rows and the second column
print()
print(a[0,:]) #Grab everything in the first row

[[2]
 [4]]

[[1 2]]


Note that all splice notation works with Numpy arrays.

You can also do operations on all elements of a Numpy array at the same time. This is shown below and is called vectorization.

In [106]:
print(a + 1)
print()
print(3*a)

[[2 3]
 [4 5]]

[[ 3  6]
 [ 9 12]]


In [107]:
print(np.multiply(a,a)) #Element-wise multiply
print()
print(np.matmul(a,a)) #True matrix multiply

[[ 1  4]
 [ 9 16]]

[[ 7 10]
 [15 22]]


There are plenty of Numpy operations that we are not covering, but we will see more of these as we go throughout the class. For more details, go to https://docs.scipy.org/doc/numpy/reference/ .